[DSD-5354] updated push-trigger.yml
Signed-off-by: Rakshithb1 <rakshit.b@technoforte.co.in>

diff --git a/.github/workflows/push-trigger.yml b/.github/workflows/push-trigger.yml
--- a/.github/workflows/push-trigger.yml
+++ b/.github/workflows/push-trigger.yml
@@ -66,11 +66,19 @@ jobs:
         run: |
           # Display mosip_master_container logs
           docker logs -f mosip_master_container
-      - name: Setup branch and env
+
+      - name: Set environment variables
         run: |
-          # Strip git ref prefix from version
-          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
-          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
+          if [ "${{ github.event_name }}" = "pull_request" ]; then
+            REPO_URL="${{ github.event.pull_request.head.repo.clone_url }}"
+            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
+          else
+            REPO_URL="https://github.com/${{ github.repository }}.git"
+            BRANCH_NAME="${{ github.ref_name }}"
+          fi
+          echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV
+          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+
       - name: Run masterdata-loader
         run: |
           docker run -itd \
@@ -80,18 +88,10 @@ jobs:
             -e DB_USER=masteruser \
             -e DB_PORT=5432 \
             -e DB_PWD=${{ env.DBUSER_PWD }} \
-            -e xls_folder=mosip_master \
+            -e REPOSITORY=${{ env.REPO_URL }}\
             -e BRANCH=${{ env.BRANCH_NAME }} \
             mosipdev/masterdata-loader:develop
-          
-      - name: Check whether masterdata_loader has errors in Logs
-        run: |
-          if docker logs -f masterdata_loader | grep -q "ERROR"; then
-            echo "Error found in masterdata_loader logs."
-            exit 1
-          else
-            echo "No errors found in masterdata_loader logs."
-          fi
+
 
       - name: docker ps command
         run: docker ps -a
@@ -99,3 +99,12 @@ jobs:
         run: |
           # Display masterdata_loader logs
           docker logs -f masterdata_loader
+
+      - name: Check whether masterdata_loader has errors in Logs
+        run: |
+          if docker logs  masterdata_loader | grep  -qi "error"; then
+            echo "Error found in masterdata_loader logs."
+            exit 1
+          else
+            echo "No errors found in masterdata_loader logs."
+          fi    
