nigga

diff --git a/.github/workflows/push-trigger.yml b/.github/workflows/push-trigger.yml
--- a/.github/workflows/push-trigger.yml
+++ b/.github/workflows/push-trigger.yml
@@ -102,11 +102,11 @@ jobs:
           # Display masterdata_loader logs
           docker logs -f masterdata_loader
 
-          #- name: Check whether masterdata_loader has errors in Logs
-          #run: |
-          #if docker logs  masterdata_loader | grep  -qi "error"; then
-          #  echo "Error found in masterdata_loader logs."
-          #  exit 1
-          #else
-          #  echo "No errors found in masterdata_loader logs."
-          #fi    
+          - name: Check whether masterdata_loader has errors in Logs
+          run: |
+          if docker logs  masterdata_loader | grep  -qi "error"; then
+            echo "Error found in masterdata_loader logs."
+            exit 1
+          else
+            echo "No errors found in masterdata_loader logs."
+          fi    
